# Generated by Django 6.0.6 on 2026-06-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeur',
            name='role',
            field=models.CharField(choices=[('Demandeur', 'Demandeur'), ('Chef', 'Chef Direct'), ('Logistique', 'Responsable Logistique'), ('Directeur', 'Directeur')], default='Demandeur', max_length=20),
        ),
    ]
