# Generated by Django 5.2.2 on 2026-06-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_alter_chauffeur_id_alter_demandeur_id_and_more'),
        ('vehicule', '0002_alter_demandeur_role'),
    ]

    operations = [
    ]
