# Generated by Django 5.2.2 on 2026-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0003_merge_20260618_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
