# Generated by Django 5.2.10 on 2026-06-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0004_loginadmin_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
