# Generated by Django 6.0.6 on 2026-06-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0006_financement_alter_chauffeur_id_alter_demandeur_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='financement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs', to='vehicule.financement'),
        ),
    ]
